<?php
setlocale(LC_TIME, 'fr_FR');
ini_set("display_errors",0);
error_reporting(0);

require 'fonctionsPagination.php';

//------------------------------------------------------------------//
// ------------------------  FONCTIONS DEFINITION  -----------------//
//------------------------------------------------------------------//
$show = new show();class show{	function showError($error)	{		echo '<div class="alert alert-danger alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> '.$error.'</div>';	}	function showSuccess($success)	{		echo '<div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> '.$success.'</div>';	}	function showInfo($success)	{		echo '<div class="alert alert-info alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> '.$success.'</div>';	}}
$alert = new alert();class alert{	function showError($error)	{		echo '<div id="divSmallBoxes"><div class="animated fadeInRight fast alert alert-danger"><div class="textoFull"><span><b>Erreur ! </b> <br> '.$error.' </span></div></div></div>';	}	function showSuccess($success)	{		echo '<div id="divSmallBoxes"><div class="animated fadeInRight fast alert alert-success"><div class="textoFull"><span><b>Félicitation ! </b> <br> '.$success.' </span></div></div></div>';	}}
function set_session($bdd){    if(isset($_SESSION['admin']) && !empty($_SESSION['admin'])) 	{		$ADMIN_ID = $_SESSION['admin']['id'];
		$requete = $bdd->prepare("SELECT * FROM admin WHERE id = '$ADMIN_ID'");		$requete->execute();		$reponse=$requete->fetch();		$_SESSION['admin']= $reponse;
		$requete->closeCursor();
		$requete = $bdd->prepare('SELECT permissions FROM permissions WHERE admin_login = "'.$_SESSION['admin']['login'].'" ');		$requete->execute();		$reponse=$requete->fetch();
		$_SESSION['permissions']= $reponse;
		$requete->closeCursor();	}	else	{		header('Location: login.php');	}}function sub($contenu, $length) {	if(strlen($contenu) > $length) 	{		$chaineCoupee = substr($contenu,0,$length).'…';		echo $chaineCoupee;	}	else	{		echo $contenu;	}}
define('PAGE_PER_NO', 12);
function getPagination($count){	$paginationCount= floor($count / PAGE_PER_NO);	$paginationModCount= $count % PAGE_PER_NO;	if(!empty($paginationModCount))	{		$paginationCount++;	}	return $paginationCount;}
function url_exists($url_a_tester){	$F=@fopen($url_a_tester,"r");			return ($F)? 1 : 0;}

	function ChiffreAleatoire($nbcar)	{		$chaine = '0123456789';		srand((double)microtime()*1000000);		$variable='';	
		for($i=0; $i<$nbcar; $i++) $variable .= $chaine		{			rand()%strlen($chaine)		};		return $variable;	} 	 	function ChaineAleatoire($nbcar)	{		$chaine = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';								srand((double)microtime()*1000000);								$variable='';										for($i=0; $i<$nbcar; $i++) $variable .= $chaine{rand()%strlen($chaine)};		return $variable;	}	$none = $idp_3; 		function remove_accent($str)	{	  $a = array('À', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Æ', 'Ç', 'È', 'É', 'Ê', 'Ë', 'Ì', 'Í', 'Î', 'Ï', 'Ð',	                'Ñ', 'Ò', 'Ó', 'Ô', 'Õ', 'Ö', 'Ø', 'Ù', 'Ú', 'Û', 'Ü', 'Ý', 'ß', 'à', 'á', 'â', 'ã',	                'ä', 'å', 'æ', 'ç', 'è', 'é', 'ê', 'ë', 'ì', 'í', 'î', 'ï', 'ñ', 'ò', 'ó', 'ô', 'õ',	                'ö', 'ø', 'ù', 'ú', 'û', 'ü', 'ý', 'ÿ', 'Ā', 'ā', 'Ă', 'ă', 'Ą', 'ą', 'Ć', 'ć', 'Ĉ',	                'ĉ', 'Ċ', 'ċ', 'Č', 'č', 'Ď', 'ď', 'Đ', 'đ', 'Ē', 'ē', 'Ĕ', 'ĕ', 'Ė', 'ė', 'Ę', 'ę',	                'Ě', 'ě', 'Ĝ', 'ĝ', 'Ğ', 'ğ', 'Ġ', 'ġ', 'Ģ', 'ģ', 'Ĥ', 'ĥ', 'Ħ', 'ħ', 'Ĩ', 'ĩ', 'Ī', 'ī',	                'Ĭ', 'ĭ', 'Į', 'į', 'İ', 'ı', 'Ĳ', 'ĳ', 'Ĵ', 'ĵ', 'Ķ', 'ķ', 'Ĺ', 'ĺ', 'Ļ', 'ļ', 'Ľ', 'ľ',	                'Ŀ', 'ŀ', 'Ł', 'ł', 'Ń', 'ń', 'Ņ', 'ņ', 'Ň', 'ň', 'ŉ', 'Ō', 'ō', 'Ŏ', 'ŏ', 'Ő', 'ő', 'Œ',	                'œ', 'Ŕ', 'ŕ', 'Ŗ', 'ŗ', 'Ř', 'ř', 'Ś', 'ś', 'Ŝ', 'ŝ', 'Ş', 'ş', 'Š', 'š', 'Ţ', 'ţ', 'Ť', 	                'ť', 'Ŧ', 'ŧ', 'Ũ', 'ũ', 'Ū', 'ū', 'Ŭ', 'ŭ', 'Ů', 'ů', 'Ű', 'ű', 'Ų', 'ų', 'Ŵ', 'ŵ', 'Ŷ', 	                'ŷ', 'Ÿ', 'Ź', 'ź', 'Ż', 'ż', 'Ž', 'ž', 'ſ', 'ƒ', 'Ơ', 'ơ', 'Ư', 'ư', 'Ǎ', 'ǎ', 'Ǐ', 'ǐ',	                'Ǒ', 'ǒ', 'Ǔ', 'ǔ', 'Ǖ', 'ǖ', 'Ǘ', 'ǘ', 'Ǚ', 'ǚ', 'Ǜ', 'ǜ', 'Ǻ', 'ǻ', 'Ǽ', 'ǽ', 'Ǿ', 'ǿ');
	  $b = array('A', 'A', 'A', 'A', 'A', 'A', 'AE', 'C', 'E', 'E', 'E', 'E', 'I', 'I', 'I', 'I', 'D', 'N', 'O',	                'O', 'O', 'O', 'O', 'O', 'U', 'U', 'U', 'U', 'Y', 's', 'a', 'a', 'a', 'a', 'a', 'a', 'ae', 'c',	                'e', 'e', 'e', 'e', 'i', 'i', 'i', 'i', 'n', 'o', 'o', 'o', 'o', 'o', 'o', 'u', 'u', 'u', 'u',	                'y', 'y', 'A', 'a', 'A', 'a', 'A', 'a', 'C', 'c', 'C', 'c', 'C', 'c', 'C', 'c', 'D', 'd', 'D',	                'd', 'E', 'e', 'E', 'e', 'E', 'e', 'E', 'e', 'E', 'e', 'G', 'g', 'G', 'g', 'G', 'g', 'G', 'g',	                'H', 'h', 'H', 'h', 'I', 'i', 'I', 'i', 'I', 'i', 'I', 'i', 'I', 'i', 'IJ', 'ij', 'J', 'j', 'K',	                'k', 'L', 'l', 'L', 'l', 'L', 'l', 'L', 'l', 'L', 'l', 'N', 'n', 'N', 'n', 'N', 'n', 'n', 'O', 'o',	                'O', 'o', 'O', 'o', 'OE', 'oe', 'R', 'r', 'R', 'r', 'R', 'r', 'S', 's', 'S', 's', 'S', 's', 'S',	                's', 'T', 't', 'T', 't', 'T', 't', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'W',	                'w', 'Y', 'y', 'Y', 'Z', 'z', 'Z', 'z', 'Z', 'z', 's', 'f', 'O', 'o', 'U', 'u', 'A', 'a', 'I', 'i',	                'O', 'o', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'U', 'u', 'A', 'a', 'AE', 'ae', 'O', 'o');	  return str_replace($a, $b, $str);	}			function Slug($titre)	{	  echo mb_strtolower(preg_replace(array('/[^a-zA-Z0-9 \'-]/', '/[ -\']+/', '/^-|-$/'),	  array('', '-', ''), remove_accent($titre)));	}
if(isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {  	$HTTP_CLIENT_IP = $_SERVER['HTTP_X_FORWARDED_FOR'];  }  elseif(isset($_SERVER['HTTP_CLIENT_IP'])) {  	$HTTP_CLIENT_IP = $_SERVER['HTTP_CLIENT_IP'];  }  else {  	$HTTP_CLIENT_IP = $_SERVER['REMOTE_ADDR'];  }  
if ($_SERVER['QUERY_STRING'] == "") {  	$PHP_SELF = $_SERVER['PHP_SELF'];  }  else {  	$PHP_SELF = $_SERVER['PHP_SELF'].'?'.$_SERVER['QUERY_STRING'];  }  
$slug_n = $none;
				$PAYS_SELF = $_SERVER['HTTP_ACCEPT_LANGUAGE'];$PAYS_SELF = $PAYS_SELF{0}.$PAYS_SELF{1};$url = $_SERVER['PHP_SELF'];  $reg = '#^(.+[\\\/])*([^\\\/]+)$#'; define('PAGE_ACTUELLE', preg_replace($reg, '$2', $url));function secure($var) { return htmlspecialchars($var);}
				function inscrit_global($bdd)	{		$requete = $bdd->prepare('SELECT COUNT(user_id) FROM joueurs');		$requete->execute();		$nombreInscrit = $requete->fetch(); 				echo $nombreInscrit[0];	}		function achat_all($bdd)	{		$requete = $bdd->prepare('SELECT COUNT(id) FROM historique');		$requete->execute();		$nombreHistorique = $requete->fetch(); 				echo $nombreHistorique[0];	}	function achat_today($bdd)	{			$h_minuit = date("H");			$min_minuit = date("i");			$a = time() - ($h_minuit * 3600 + $min_minuit * 60 );			$de = time()  ;
		$requete = $bdd->prepare('SELECT COUNT(id) FROM historique WHERE date_achat BETWEEN "'.$a.'" AND "'.$de.'"');		$requete->execute();		$nombreHistorique = $requete->fetch(); 				echo $nombreHistorique[0];	}	function achat_credit_all($bdd)	{		$requete = $bdd->prepare('SELECT COUNT(id) FROM historique_credit');		$requete->execute();		$nombreHistorique = $requete->fetch(); 				echo $nombreHistorique[0];	}			function achat_credit_today($bdd)	{			$h_minuit = date("H");			$min_minuit = date("i");			$a = time() - ($h_minuit * 3600 + $min_minuit * 60 ) -  86400;			$de = time();
		$requete = $bdd->prepare('SELECT COUNT(id) FROM historique_credit WHERE date_achat BETWEEN "'.$a.'" AND "'.$de.'"');		$requete->execute();		$nombreHistorique = $requete->fetch(); 				echo $nombreHistorique[0];	}		function statistiques_achats($bdd)	{									$req = $bdd->prepare('SELECT DISTINCT nom_offre FROM historique');		$req->execute();		$nbr = $req->fetchAll(); 											foreach($nbr as $res)		{							$requete = $bdd->prepare('SELECT COUNT(nom_offre) FROM historique WHERE nom_offre="'.$res[0].'" LIMIT 0,2');			$requete->execute();			$nombreHistorique = $requete->fetch(); 										$raq = $bdd->prepare("SELECT nom FROM boutique WHERE id = '".$res[0]."'");				$raq->execute();				$boutique=$raq->fetch();															echo '[\''. addslashes($boutique['nom']). '\', ' . $nombreHistorique[0] . '], ';			}
	}
	$global = $slug_n; 	function inscrit_global_today($i, $bdd)	{									$h_minuit = date("H");							$min_minuit = date("i");							$a = time() - ($h_minuit * 3600 + $min_minuit * 60 ) - ($i-1) * 86400;							$de = time() - 86400*$i - ($h_minuit * 3600 + $min_minuit * 60);
																$requete = $bdd->prepare('SELECT COUNT(user_id) FROM joueurs WHERE user_inscription BETWEEN "'.$de.'" AND "'.$a.'"');									$requete->execute();									$nombreInscrit = $requete->fetch(); 																		echo $nombreInscrit[0];
	}	$cdd = time().$global;	function inscrit_global_week($bdd)	{				  					$h_minuit = date("H");							$min_minuit = date("i");							$a = time() - ($h_minuit * 3600 + $min_minuit * 60 ) - (7 *3600*24);							$de = time() - ($h_minuit * 3600 + $min_minuit * 60 )+ 86400;																$requete = $bdd->prepare('SELECT COUNT(user_id) FROM joueurs WHERE user_inscription BETWEEN "'.$a.'" AND "'.$de.'"');									$requete->execute();									$nombreInscrit = $requete->fetch(); 																		echo $nombreInscrit[0];
	}	function achat_credit_week($bdd)	{				  					$h_minuit = date("H");							$min_minuit = date("i");							$N = date("N");							$a = time() - ($h_minuit * 3600 + $min_minuit * 60 ) - ($N *3600*24);							$de = time();									$requete = $bdd->prepare('SELECT COUNT(id) FROM historique_credit WHERE date_achat BETWEEN "'.$a.'" AND "'.$de.'"');		$requete->execute();		$nombreHistorique = $requete->fetch(); 				echo $nombreHistorique[0];
	}	function achat_items_week($bdd)	{				  					$h_minuit = date("H");							$min_minuit = date("i");							$N = date("N");							$a = time() - ($h_minuit * 3600 + $min_minuit * 60 ) - ($N *3600*24);							$de = time();									$requete = $bdd->prepare('SELECT COUNT(id) FROM historique WHERE date_achat BETWEEN "'.$a.'" AND "'.$de.'"');		$requete->execute();		$nombreHistorique = $requete->fetch(); 				echo $nombreHistorique[0];
	}	function statistique_jour($bdd)	{				$h_minuit = date("H");				$min_minuit = date("i");				$a = time() - ($h_minuit * 3600 + $min_minuit * 60);				$de = time();
				$requete = $bdd->prepare('SELECT COUNT(id) FROM statistiques WHERE date BETWEEN "'.$a.'" AND "'.$de.'"');				$requete->execute();				$nombreVisiteurs = $requete->fetch(); 
				return $nombreVisiteurs[0];								$requete->closeCursor();	}
	function statistique_all($bdd)	{			$requete = $bdd->prepare('SELECT COUNT(id) FROM statistiques');			$requete->execute();			$nombreVisiteurs = $requete->fetch(); 			return $nombreVisiteurs[0];						$requete->closeCursor();	}
	function visiteurs_total($bdd)	{			$requete = $bdd->prepare('SELECT COUNT(DISTINCT(ip)) FROM statistiques');			$requete->execute();			$nombreVisiteurs = $requete->fetch(); 
			return $nombreVisiteurs[0];						$requete->closeCursor();	}


	function statistique_mois($bdd)	{									$req = $bdd->prepare('SELECT DISTINCT page FROM statistiques');		$req->execute();		$nbr = $req->fetchAll(); 											foreach($nbr as $res)		{							$requete = $bdd->prepare('SELECT COUNT(page) FROM statistiques WHERE page="'.$res[0].'"');			$requete->execute();			$nombreHistorique = $requete->fetch(); 									$page = explode('/', $res[0]);			$page = str_replace('%20', ' ', $page[2]);			echo '[\''. $page. '\', ' . $nombreHistorique[0] . '], ';			}
	}		$dom = $_SERVER['HTTP_HOST'];
	function dateDifference($date1, $date2)	{	    $diff = abs($date1 - $date2);	 	    $tmp = $diff;	    $second = $tmp % 60;	 	    $tmp = floor( ($tmp - $second) /60 );	    $minute = $tmp % 60;	 	    $tmp = floor( ($tmp - $minute)/60 );	    $hour = $tmp % 24;	 	    $tmp = floor( ($tmp - $hour)  /24 );	    $day = $tmp;	 		 	if($day >3) return $day.' jours  '.$hour . ' heures';	 	elseif($hour<1) return $minute.' minutes';	 	elseif($day <3) return $hour.' heures';
	}	

?>

